Update to prevent 'Uncaught TypeError: $ is not a function' errors
Update to prevent 'Uncaught TypeError: $ is not a function' errors via pjax calls on GridView filters etc



Yii Framework 2.0.13.1